config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do

  # Static pages
  match '/projects/album_generator', to: 'projects#albums', via: :all
  get '/projects' => 'projects#index', as: 'projects'
  get '/photography' => 'pages#photography', as: 'photography'
  get '/map' => 'pages#map', as: 'map', via: :get
  get '/t' => 'pages#date', as: 'date'
  
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  get 'robots.:format' => 'robots#index'
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  root 'pages#home'
end

app/views/pages/date.html.erb
<script>

var start = new Date('<%="#{@start}"%>').getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get todays date and time
  var now = new Date().getTime();

  // Find the distance between now an the count down date
  var distance = now - start;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("t").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";

  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>
<div class="container">
<h1 id="t"></h1>
</div>

app/views/pages/home.html.erb
<script type="application/ld+json">
  {
  "@context" : "http://schema.org",
  "@type" : "WebSite",
  "name" : "MWAhmed",
  "alternateName" : "Mohammad Ahmed",
  "url" : "http://www.mwahmed.com"
  }
</script>

<div class="container text-center" id="home-about">
	<br>
	<p> Hello, I'm Mohammad. </p>

	<p> I am a software engineer currently living in Toronto, Canada.</p>

	<p> Contact details <a href="/contact"> here</a>.</p>
</div>

app/views/pages/home.html.haml
%script{:type => "application/ld+json"}
  {
  "@context" : "http://schema.org",
  "@type" : "WebSite",
  "name" : "MWAhmed",
  "alternateName" : "Mohammad Ahmed",
  "url" : "http://www.mwahmed.com"
  }

:javascript
  $(document).ready(function() {
      $('body').addClass('background');
  });  

app/views/pages/map.html.erb
<h1> Images classified by location</h1>
<p> Click on a marker to start a slideshow of images taken nearby that particular location. Scroll to access zoom features of the map </p>
<%= social_share_button_tag() %> 
<div id="world-map"></div>
<% @img_with_loc.keys.each do |k| %>  
  <div id="<%=k.join('-')%>" style="display: none;">
      <div id="gallery-<%=k.join('-')%>">
        <% @img_with_loc[k].each_with_index do |el, index| %>
          <a id="img<%=k.join('-')%><%=index%>" href="<%=el[0]%>"  title="<%=el[1]%>">
            <img class="galler-image" src=<%=el[0]%>/>
          </a>
        <% end %> 
      </div>
  </div>  
<%end%>
<script type="text/javascript"> 
   jQuery(document).ready(function() {
       jQuery('#world-map').empty();

       var modal_options = {
           "backdrop": "static"
       }
       var markers = [];


       <%@img_with_loc.keys.each do |k| %>
       var location = {
           latLng: [<%=k[0]%>, <%=k[1]%>],
           name: "",
           key: "<%=k.join('-')%>"
       };
       markers.push(location);
       <%end%>

       jQuery('#world-map').vectorMap({
           map: 'world_mill_en',
           scaleColors: ['#C8EEFF', '#0071A4'],
           normalizeFunction: 'polynomial',
           hoverOpacity: 0.7,
           hoverColor: true,
           markerStyle: {
              initial: {
                fill: '#3EA055',
                stroke: '#505050',
                "fill-opacity": 2,
                "stroke-width": 2,
                "stroke-opacity": 2,
                r: 5
              },
              hover: {
                stroke: 'black',
                "stroke-width": 2,
                cursor: 'pointer'
              },
              selected: {
                fill: 'blue'
              },
              selectedHover: {
              }
           },
           backgroundColor: '#566D7E',
           markers: markers,
           onMarkerClick: function(e, index) {
               var galleryId = "#gallery-" + markers[index].key;
               var imgId = "#img" + markers[index].key + "0";
               $(galleryId).each(function() {
                   $(this).magnificPopup({
                       removalDelay: 300,
                       mainClass: 'mfp-with-zoom mfp-img-mobile',
                       image: {
                           verticalFit: true,
                           titleSrc: function(item) {
                               return item.el.attr('title');
                           }
                       },
                       delegate: 'a',
                       type: 'image',
                       gallery: {
                           enabled: true
                       },
                       zoom: {
                           enabled: true,
                           duration: 300,
                           opener: function(element) {
                               return element.find('img');
                           }
                       }
                   });
               });
               $(imgId).trigger('click');
               
           }
       });
       jQuery('g circle').tooltip();
   });
     
</script>
<p> Map powered by <a href="http://jvectormap.com/">JVectormap </a></p>

app/views/pages/photography.html.erb
<script type="text/javascript">
$(document).ready(function() {
  
  $('.galler-image').each(
    function(){
        var src = $(this).attr('src');
        if (src.slice(-1) == "/") {
          this.src = src.slice(0,-1);  
        }
  });

  $("#gallery").justifiedGallery({
        'usedSuffix': 'lt240',
        'justifyLastRow': false,
        'rowHeight': 200,
        'fixedHeight': false,
        'captions': false,
        'margins': 1
    });

  $('#gallery').each(function() { 
    $(this).magnificPopup({
        removalDelay: 300,
        mainClass: 'mfp-with-zoom mfp-img-mobile',
        image: {
          verticalFit: true,
          titleSrc: function(item) {
            return item.el.attr('title');
          }
        },
        delegate: 'a',
        type: 'image',
        gallery: {
          enabled:true
        },
        zoom: {
          enabled: true,
          duration: 300, 
          opener: function(element) {
            return element.find('img');
          }
        }
    });
  });

});
</script>
<pre> Related: <%= link_to "Map view", map_path, :class => "btn btn-custom"%></pre> 

<div class="container fluid"> 
    
    <h1> Photography </h1>
    <p>I do photography as a hobby and put some of the popular ones here. </p>
    <p>I shoot with Canon EOS Rebel T3, EF-S 18-55mm, EF-S 55-250mm.</p>
  <div class="text-right"> 
    <%= paginate @images %>
  </div>
  <div id="gallery" >
    <% @images.each do |img| %>
      <a href=<%=img["url"] %>  alt='<%=img["title"] %>' title='<%=img["title"] %>'>
          <img class="galler-image" src=<%== img["url"] %>/>
      </a>
    <% end %> 
  </div>
  <div class="text-right"> 
    <%= paginate @images %>
    <%= social_share_button_tag() %> 
  </div>
</div>