config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do

  # Static pages
  match '/projects/album_generator', to: 'projects#albums', via: :all
  get '/projects' => 'projects#index', as: 'projects'
  get '/photography' => 'pages#photography', as: 'photography'
  get '/map' => 'pages#map', as: 'map', via: :get
  get '/t' => 'pages#date', as: 'date'
  
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  get 'robots.:format' => 'robots#index'
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  root 'pages#home'
end

app/views/layouts/_adsense1.html.haml
%script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
/ AdSense
%ins.adsbygoogle{"data-ad-client" => "ca-pub-2185232063477218", "data-ad-format" => "auto", "data-ad-slot" => "5627857282", :style => "display:block"}
:javascript
  (adsbygoogle = window.adsbygoogle || []).push({});

app/views/layouts/_adsense2.html.haml
%script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
/ AdSense2
%ins.adsbygoogle{"data-ad-client" => "ca-pub-2185232063477218", "data-ad-format" => "auto", "data-ad-slot" => "9778855285", :style => "display:block"}
:javascript
  (adsbygoogle = window.adsbygoogle || []).push({});

app/views/layouts/_airbrake.html.haml
- if defined?(Airbrake) && Airbrake.configuration.js_api_key.present?
  = airbrake_javascript_notifier

app/views/layouts/_analytics.html.haml
:javascript
	
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-67198493-1', 'auto');
	ga('send', 'pageview');

app/views/layouts/_destroy_modal.html.haml
- id ||= 'destroy-modal'
- i18n_prefix = i18n_prefix.present? ? "#{i18n_prefix}." : ''

.modal.fade{id: id, tabindex: -1, role: 'dialog', 'aria-labelledby' => "#{id}-title", 'aria-hidden' => true}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: 'modal'}, 'aria-hidden' => true} &times;
        %h4{id: "#{id}-title"}= I18n.t "#{i18n_prefix}prompt"
      .modal-body
        - warning = I18n.t "#{i18n_prefix}warning"
        - if warning.present?
          .alert.alert-danger
            %i.glyphicon.glyphicon-warning-sign.text-danger
            = warning
        %p= I18n.t "#{i18n_prefix}notice"
      .modal-footer
        %button.btn.btn-danger{data: {confirm: '', dismiss: 'modal'}}= I18n.t "#{i18n_prefix}submit"
        %button.btn.btn-default{data: {dismiss: 'modal'}}= I18n.t "#{i18n_prefix}cancel"

app/views/layouts/_footer.html.erb
<nav class="navbar-default navbar-fixed-bottom"> 
    <p>Copyright <%= $copyright_year %> <%=icon('copyright')%> MWAhmed</p>
</nav>

app/views/layouts/_image_protection.html.haml
:javascript

	//<![CDATA[
	function nocontext(e) {
	var clickedTag = (e==null) ? event.srcElement.tagName : e.target.tagName;
	if (clickedTag == "IMG") {
	return false;
	}
	}
	document.oncontextmenu = nocontext;
	window.ondragstart = function() { return false; } 
	//]]>

app/views/layouts/_javascripts.html.haml
-# JavaScripts included in <body> for initializing Backbone views, etc.

-# Immediately executable javascript
- if content_for? :javascript
  = yield :javascript

-# Document ready javascript
- if content_for? :on_ready
  :javascript
    head.ready(function(){
      #{yield :on_ready}
    })

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String) and msg.present?
    - type = (['info', 'success', 'warning', 'danger'].include?(name.to_s) ? name : 'info')
    .alert.alert-dismissable{class: "alert-#{type}"}
      %button.close{'data-dismiss' => 'alert', 'aria-hidden' => true} &times;
      = msg

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
  .navbar-header
    %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '.navbar-collapse'}}
      %span.sr-only
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'MWAhmed', root_path, class: 'navbar-brand'

  .collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      %li= link_to 'Photography', photography_path
      %li= link_to 'Contact', contact_path

app/views/layouts/application.html.haml
!!!
%html.no-js{lang: 'en'}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}
    %meta{:content => "01-c8ej7l0rhi5wnzfkvgakn7p3i0cbhiyl7tp1rbf-v7n2ihlo6n5m3ojfc75tukm62238-xkpmapppzo9fx6drj2582dpdtkvra-egibqcm6yuw-pd3hlf883onru2", :name => "norton-safeweb-site-verification"}/
    %title= @title.blank? ? "MWAhmed" : @title
    %meta{content: (content_for?(:description) ? yield(:description) : I18n.t('brand.name')), name: 'description'}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    /[if lt IE 9]
      = javascript_include_tag 'ie', 'data-turbolinks-track' => true
    = javascript_include_tag 'head', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    /[if lt IE 9]
      = javascript_include_tag 'ie'
    
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico' 
    = yield :head
    = render 'layouts/airbrake'
  %body{class: "controller__#{controller_name}_action__#{action_name}"}
    = render 'layouts/navigation'
    = render 'layouts/image_protection'
    .container-fluid.fill
      .errors__container
        = render 'layouts/messages'
      = yield
      %footer.page__footer
        = render 'layouts/footer'
    = render 'layouts/analytics'
    = render 'layouts/javascripts'

app/views/layouts/uncaught_error.js.haml
:plain
  var $wrap = $('.errors__container').empty()
  $wrap.append('#{escape_javascript(render 'layouts/messages')}')
  if ($wrap.length && typeof $.scrollTo == 'function') {
    $.scrollTo($wrap.offset().top - parseInt($('body').css('padding-top')), 300)
  }